---
title: "STAT Final Report - Wine Dataset"
author: "Group 4"
date: "November 27, 2018"
output: pdf_document
---

####Introduction to the dataset:
\t The two datasets are related to red and white variants of the Portuguese "Vinho Verde" wine. We obtained the dataset from: http://archive.ics.uci.edu/ml/datasets/Wine+Quality . The website also provided the following references.\newline
1. Paulo Cortez, University of Minho, Guimar?es, Portugal, http://www3.dsi.uminho.pt/pcortez \space
2. A. Cerdeira, F. Almeida, T. Matos and J. Reis, Viticulture Commission of the Vinho Verde Region(CVRVV), Porto, Portugal,2009.
\t We randomly select 1000 samples of the dataset. It contains the following variables (units are not given in the dataset description): 

+ fixed acidity (grams/liter)
* volatile acidity (grams/liter)
* citric acid (grams/liter)
* residual sugar (grams/liter)
* chlorides (grams/liter)
* free sulfur dioxide (milligrams/liter)
* total sulfur dioxide (milligrams/liter)
* density (grams/cubic centimeter)
* pH: acidity (below 7) or alkalinity (over 7)
* sulphates:potassium sulfate (grams/liter)
* alcohol:percentage alcohol (% volume)
+ Output variable (based on sensory data): quality (score between 0 and 10) 

\newline
\t In this report, we are interested in what impact the different qulity of red wine and white wine. We build two different models, treating quality as continuous variable and categorical variable regardingly. Here are some simple summary output of this dataset:



####Check Collinearity and Re-Scaling X's

####Assumption Check and Potential Outlier

####Regression Model treating Quality as continuous Variable and Model Selection

####Logistic Model treating Quality as Categorical Variable and Model Selection

####Summary